[package]
name = "zg-dump"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "3.0.0-rc.9", features = ["derive", "wrap_help"] }
hex = "0.4"
anyhow = "1"
bytes = "1"
nom = "7"
nom-bufreader = "0.2.0"
itertools = "0.10"
quick-xml = "0.22"